[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "bist-dp-lstm-trading"
version = "0.1.0"
description = "BIST Trading System with DP-LSTM"

[tool.black]
line-length = 100

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--cov=src"
